"""
Sets what files will be imported when from ids import * gets called
changed last: 28/12/2019
"""
# DO NOT EDIT!
# This file was automatically generated by "generate_id_constants_from_stableid.py"

__all__ = ["unit_typeid", "ability_id", "upgrade_id", "buff_id", "effect_id"]
